// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace MMGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Rolling);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_GeneralAction);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Death);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Aiming);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Hit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Blocking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Parrying);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Parried);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_BackAttacked);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Stunned);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Dodge);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_Equip);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_Unequip);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_HitReaction);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_BlockingHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_ParriedHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_BackAttackHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_KnockBackHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_MaxPostureHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_Dodge);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Light);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Heavy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Running);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Special);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_BackAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_ParryingAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_RangedAttack);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Fire);
}